language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"  == "dhis2/dhis2-usage-analytics" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ;then 
    mvn clean deploy --settings deploy/settings.xml && echo "Deploy complete" && exit 0; 
  else
    echo "Skipped deploy, $TRAVIS_BRANCH, $TRAVIS_TAG, $TRAVIS_REPO_SLUG, $TRAVIS_PULL_REQUEST" && exit 0;
  fi
env:
  global:
  - secure: HRT3uGKkdIm8fVngwAemxIa5/SFs07Vmx1q4Wd5iBSPWZS8nyUqaIWHyKekRipx5356Kplf56fH+46FK+6ajVv4tqBEFb2AIlMOFsoFzTtzdUHlSvbxgURp/RjUZX1H7TQW6px4xZHOfVOLrgQ2sJ26yDeQQD9Ts8GgQwHPflkhT4w3S0Awxkud1VHdSl8gdtWkZ3hHyU8DVxOozT8wg2w8EEHDAjRMvrV35Qfey1WCtY+qUMw+5c5qXEU+jD3bu7fIUje51Q4WFNBfRzCjZyIh5101W9Lk8BeQPzzMg966k839NsGVeiWQa0GOddP0v1lQUtBiA2BjU63VvL0HxPQtmpDYX9gbCAOHeBdjMKsoERK8DhpJr44wACIboyHo3JyYQ75BxRdGiWN2kap0t2+Eeqhg1cOHYnb81DyNT1hlinkpjmHpCRYJ8PM1vUZmCT0mqPgzFPllQaAS1+tEnjWTgTTqZQqBmJ5/GEMY83v6gP4R3G3qlFGs3wZWGE2vOKW1elwhgUunYcPXo5sQOdGLDGrXnrwyFORJLPNvEkQTdlkChZxgPBQupISVjlEwMJQLuEdakgw0lfD7GsHe5QE7PKy6wDJyg+ZnL8Ag5RC5e4UReZ24KwMxuAp/MCG+byqq/TJWhCa4eMinDlxKLltM7thvi9RO4F42YCDjFpdw=
  - secure: SAjLI6CTqTjdxsWGxG5i7sg3o3qf3xQhnDKEhYli1Aaf0bGicTOFkUCrXpxtJMWUhkq+c/VeiHp16JepBIFe+hG+3G6ADHZKfF8mxiGG91LHpuCg93om1nxk9FZi1RKu3COEFlK8tOrl8Mgof67xgjeSf1xzzpdRNvbhJUT8I4q1Wk364DlYJ7ZUaJs+nWsV/qrZ963DiMvKqHJM9zJZ9Kvl/NY9bUjdEgBdwE7+R1n3iTGxTuK02+l4UbORLDhmrI/N0oVD2JrzJOXERgtXuree79B7v++jXHZbtYED55P4jI69l9aR8tFesBIKT2XgG+KrY2+kIQVfRAax7AoKCd3ewj5lVr8Xpd3dZA8aFAF893Ah8/XSFvjSaFMEumXCYEj4zBe6Zb5JsSsyR9xWH0We9Q99mVAH9g63iNAvvUbn9flFbA9VbAG8VReneWJyxsDEMbFQpm2VMF3ayUi3p7cdFy8LZTU9cnExnk3/KrCdaLaBj1vxyBFt3VIxBOu0gRf1zBjSGTEpOPuDiLf6a92aC5cVqwA7SpBpbhHMmtPbb2ZytYz64sJJ5sWycWH9Q+blThmodIGcZynrZ+l2PvI8CNA/NCCvMRtzTglTR5VRgPXf1n0gNdkIVLkC4s3aPswFa+tMWV+u1KKVZT0gIT/LjUu4Ev63X5Kg8DwkddA=

